language: python

# Matrix approach here due to: https://github.com/travis-ci/travis-ci/issues/9815
matrix:
    include:
      - python: 3.6
        dist: trusty
      - python: 3.7
        dist: xenial

install:
  - pip install -r requirements.txt

script:
  # Let's ignore E501 (line too long) warnings for now.
  - flake8 --ignore=E501 .
